= Bases de Datos I: Trabajo Práctico 1
Liz Moreno López <lilita.moreno@hotmail.com>; Micaela Vera <micavera2010@hotmail.com>; Veronica Juarez <veronicajuarez01@hotmail.com>
{docdate}. Docentes Daniel Rondelli,  Mariano  (COM-08)
:numbered:
:source-highlighter: highlight.js
:tabsize: 4

Se debe ser breve, conciso, y simple. Se debe incluir sólo lo relevante
que ayude a entender el trabajo práctico. Ok

== Introducción

En este trabajo práctico debemos diseñar un modelo de datos relativo a operaciones de tarjetas de crédito. Las tarjetas no permiten 
a los usuarios financiar una compra en cuotas, todo se realiza en un solo pago. Una persona puede tener más de una tarjeta pero no 
deben existir extensiones de la misma. Las tarjetas podrán estar expiradas en su fecha de vencimiento.
Las tarjetas tendrán consumos que deben surgir a partir de las compras que se realicen en los distintos comercios. 
También, nos interesan los datos de los clientes, de las tarjetas de crédito con sus vencimientos y límites, entre otros. (ver)


*(Longitud: 3–5 párrafos)*

== Descripción

[source, sql]
----
create table alumno (legajo int, nombre text, apellido text);
----

En esta sección pueden incluirse las dificultades que tuvieron, las
soluciones encontradas, y las decisiones que fueron tomando a lo largo
del trabajo práctico.

También, se debe incluir una descripción general del programa—cómo
funciona.

*(Longitud: 3–5 párrafos)*

== Implementación

En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde. Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
descripción general, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

*(Longitud: lo que sea necesario)*

== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos. También se debe
incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.

*(Longitud: 1–3 párrafos)*
