= Bases de Datos I: Trabajo Práctico 1
Liz Moreno López <lilita.moreno@hotmail.com>; Micaela Vera <micavera2010@hotmail.com>; Verónica Juarez <veronicajuarez01@hotmail.com>
{docdate}. Docentes Hernán Rondelli y Mariano Trigila (COM-01)
:numbered:
:source-highlighter: highlight.js
:tabsize: 4

Se debe ser breve, conciso, y simple. Se debe incluir sólo lo relevante
que ayude a entender el trabajo práctico. Ok

== Introducción

En este trabajo práctico debemos diseñar un modelo de datos relativo a operaciones de tarjetas de crédito. Las tarjetas no permiten 
a los usuarios financiar una compra en cuotas, todo se realiza en un solo pago. Una persona puede tener más de una tarjeta pero no 
deben existir extensiones de la misma. Las tarjetas podrán estar expiradas en su fecha de vencimiento.
Las tarjetas tendrán consumos que deben surgir a partir de las compras que se realicen en los distintos comercios. 
También, nos interesan los datos de los clientes, de las tarjetas de crédito con sus vencimientos y límites, entre otros. (ver)


*(Longitud: 3–5 párrafos)*

== Descripción

[source, sql]
----
create table alumno (legajo int, nombre text, apellido text);
----

En esta sección pueden incluirse las dificultades que tuvieron, las
soluciones encontradas, y las decisiones que fueron tomando a lo largo
del trabajo práctico.

También, se debe incluir una descripción general del programa—cómo
funciona.

*(Longitud: 3–5 párrafos)*

== Implementación
A continuación se exponen los schemas de las tablas diseñadas como así la explicación de los atributos incorporados en dichas tablas. Además, se especificarán las correspondientes *Primary Key* (_PK_) y *Foreign Key* (_FK_) de cada tabla.

=== Tabla cliente
En primer lugar, diseñamos una tabla *cliente*, los atributos que tienen lugar en este modelo son el _dni_ que será el identificador único de dicha tabla, es decir, es la _primary key_. Luego, se tienen los datos necesarios del cliente, los cuales son el _nombre_, _apellido_ y la _dirección_, además, se debe especificar el _número de teléfono_ para que el Call Center pueda notificar al cliente de un posible fraude con su tarjeta.

[source, sql]
----
create table cliente(
        dni integer,
        nombre varchar(64),
        apellido varchar(64),
        direccion varchar(64),
        telefono integer
);   
----

Como nombramos anteriormente, el dni del cliente es una _primary key_ y agregamos este valor en la tabla con la siguiente sentencia:

[source, sql]
----
alter table cliente add constraint cliente_pk primary key (dni); 
----



=== Tabla tarjeta
*Tarjeta* es una tabla cuya _primary key_ es el número identificatorio de dicha tarjeta que consta de 16 dígitos, otro de los atributos de este schema son el código de seguridad que consta de 3 a 4 dígitos dependiendo del banco, el límite de compra diario de la tarjeta, es decir, el tope máximo que el banco financia a través de la tarjeta de crédito (*ver y sigue*)

[source,sql]
----
create table tarjeta(
       numero_tarjeta integer,
       dni_cliente integer,
       codigo_seguridad integer,
       limite_compra integer,
       saldo real,
       fecha_vencimiento date,
       estado_tarjeta varchar(64)      
);
----


En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde. Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
descripción general, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

*(Longitud: lo que sea necesario)*

== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos. También se debe
incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.

*(Longitud: 1–3 párrafos)*
